### ISSUE TITLE
Region is not a valid one

### ISSUE THREAD

**Issue by dgalli1** [coleman2246/pia-wg-autorenew#1]
I did try pretty mutch all the values for the region field that i could think of. (Based on the json file)
None seem to be working, which value do you expect there?

I tried
ES Valencia
es-valencia
ES

One of those should've been correct, no?

**Comment by krin-san** [comment]
@dgalli1 Have you tried `ES\ Valencia`? Servers in [piawg.py](https://github.com/coleman2246/pia-wg-autorenew/blob/master/piawg.py#L28) are grouped by `name` so you clearly need to use "ES Valencia", but that space character could cause troubles.
