### ISSUE TITLE
not really an issue, is there a recommended INTERVAL?

### ISSUE THREAD

**Issue by fma965** [coleman2246/pia-wg-autorenew#2]
not really an issue, is there a recommended INTERVAL?

Nice work with this, i was using the manual method before

Also, would it be a good idea to remove this constant file list logging ?
`print("files", os.listdir("."))`

**Comment by Ectropian** [comment]
the interval is in seconds, I put 1200 for 10 minutes, seems to be a good interval so far.

**Comment by fma965** [comment]
Thanks
